// ============================================
// MOCK DATA — Simulates REST API responses
// ============================================

export const MOCK_USERS = [
  { id: 'u1', name: 'Alex Rivera', email: 'alex@demo.com', password: 'demo123', joinedDate: '2023-03-15' },
  { id: 'u2', name: 'Jordan Kim', email: 'jordan@demo.com', password: 'demo123', joinedDate: '2023-06-22' },
  { id: 'u3', name: 'Sam Okafor', email: 'sam@demo.com', password: 'demo123', joinedDate: '2024-01-10' },
];

export const MOCK_RESTAURANTS = [
  {
    id: 'r1',
    name: 'Bella Osteria',
    cuisine: 'Italian',
    priceRange: '$$$',
    address: '142 Columbus Ave, New York, NY',
    phone: '(212) 555-0198',
    website: 'bellosteria.com',
    hours: 'Mon–Sun 12pm – 10pm',
    description: 'Award-winning Italian trattoria serving handmade pasta and wood-fired dishes in a warmly lit, intimate space. Our recipes are inspired by Nonna Lucia\'s kitchen in Bologna.',
    emoji: '🍝',
    tags: ['Pasta', 'Wine Bar', 'Date Night', 'Reservations'],
    featured: true,
    neighborhood: 'Upper West Side',
    openNow: true,
  },
  {
    id: 'r2',
    name: 'Sakura Ramen',
    cuisine: 'Japanese',
    priceRange: '$$',
    address: '88 E 4th St, New York, NY',
    phone: '(212) 555-0142',
    website: 'sakuraramen.com',
    hours: 'Mon–Sun 11am – 11pm',
    description: 'Authentic Japanese ramen house with 18-hour tonkotsu broth, seasonal toppings, and a dedicated sake bar. Small and busy — lines move fast.',
    emoji: '🍜',
    tags: ['Ramen', 'Japanese', 'Quick Eats', 'Sake'],
    featured: true,
    neighborhood: 'East Village',
    openNow: true,
  },
  {
    id: 'r3',
    name: 'The Smoky Brisket',
    cuisine: 'BBQ',
    priceRange: '$$',
    address: '305 W 45th St, New York, NY',
    phone: '(212) 555-0211',
    website: 'smokybrisket.com',
    hours: 'Tue–Sun 11am – 9pm',
    description: 'Texas-style BBQ with brisket smoked for 16+ hours over oak wood. Sides are legendary. Peach cobbler is made fresh daily.',
    emoji: '🥩',
    tags: ['BBQ', 'Smokehouse', 'Comfort Food'],
    featured: false,
    neighborhood: 'Hell\'s Kitchen',
    openNow: false,
  },
  {
    id: 'r4',
    name: 'Café Lumière',
    cuisine: 'French',
    priceRange: '$$$',
    address: '17 W 8th St, New York, NY',
    phone: '(212) 555-0176',
    website: 'cafelumiere.com',
    hours: 'Mon–Fri 8am – 10pm, Sat–Sun 9am – 11pm',
    description: 'A slice of Montmartre in Manhattan. Café Lumière serves classic French bistro fare — croissants, steak frites, bouillabaisse — in a candlelit Haussmann-inspired dining room.',
    emoji: '🥐',
    tags: ['French', 'Brunch', 'Romantic', 'Patio'],
    featured: true,
    neighborhood: 'Greenwich Village',
    openNow: true,
  },
  {
    id: 'r5',
    name: 'Spice Route',
    cuisine: 'Indian',
    priceRange: '$$',
    address: '224 Lexington Ave, New York, NY',
    phone: '(212) 555-0188',
    website: 'spiceroute.com',
    hours: 'Mon–Sun 12pm – 11pm',
    description: 'Regional Indian cuisine celebrating the diversity of the subcontinent. From Kerala fish curry to Rajasthani dal baati, each dish is a journey.',
    emoji: '🍛',
    tags: ['Indian', 'Vegetarian', 'Spicy', 'Delivery'],
    featured: false,
    neighborhood: 'Gramercy',
    openNow: true,
  },
  {
    id: 'r6',
    name: 'La Taqueria Verde',
    cuisine: 'Mexican',
    priceRange: '$',
    address: '55 Fulton St, New York, NY',
    phone: '(212) 555-0230',
    website: 'taqueriaverde.com',
    hours: 'Mon–Sun 10am – midnight',
    description: 'Authentic street tacos, salsas made in-house daily, and mezcal flights. The al pastor is worth a trip downtown any night of the week.',
    emoji: '🌮',
    tags: ['Tacos', 'Mexican', 'Late Night', 'Mezcal'],
    featured: false,
    neighborhood: 'Financial District',
    openNow: true,
  },
  {
    id: 'r7',
    name: 'Golden Dragon',
    cuisine: 'Chinese',
    priceRange: '$$',
    address: '18 Mott St, New York, NY',
    phone: '(212) 555-0165',
    website: 'goldendragonnyc.com',
    hours: 'Mon–Sun 11am – 10pm',
    description: 'Dim sum palace with over 60 varieties served all day. The har gow and egg tarts are city-famous. Come hungry, leave satisfied.',
    emoji: '🥟',
    tags: ['Dim Sum', 'Chinese', 'Family Style', 'Lunch'],
    featured: false,
    neighborhood: 'Chinatown',
    openNow: false,
  },
  {
    id: 'r8',
    name: 'The Garden Table',
    cuisine: 'American',
    priceRange: '$$$',
    address: '92 Bedford Ave, Brooklyn, NY',
    phone: '(718) 555-0120',
    website: 'thegardentable.com',
    hours: 'Wed–Sun 5pm – 10pm',
    description: 'Farm-to-table New American cuisine sourced within 100 miles of Brooklyn. The menu changes weekly based on seasonal availability. Exceptional natural wine list.',
    emoji: '🥗',
    tags: ['Farm-to-Table', 'American', 'Seasonal', 'Wine'],
    featured: true,
    neighborhood: 'Williamsburg',
    openNow: false,
  },
];

export const MOCK_REVIEWS = [
  {
    id: 'rv1',
    restaurantId: 'r1',
    userId: 'u1',
    userName: 'Alex Rivera',
    rating: 5,
    text: 'Absolutely incredible pasta. The cacio e pepe was the best I\'ve had outside of Rome — perfectly al dente, beautifully balanced. Service was warm and attentive. Will absolutely be back.',
    date: '2024-10-15',
    tags: ['Amazing Food', 'Great Service'],
    helpful: 12,
  },
  {
    id: 'rv2',
    restaurantId: 'r1',
    userId: 'u2',
    userName: 'Jordan Kim',
    rating: 4,
    text: 'Lovely atmosphere and genuinely excellent food. The pappardelle with wild boar ragù was outstanding. Only gripe is the wait for reservations — book weeks ahead.',
    date: '2024-09-28',
    tags: ['Romantic', 'Book Ahead'],
    helpful: 7,
  },
  {
    id: 'rv3',
    restaurantId: 'r1',
    userId: 'u3',
    userName: 'Sam Okafor',
    rating: 5,
    text: 'I had the tasting menu and every course was a revelation. The sommelier\'s wine pairing was exceptional. Special occasion dining at its finest.',
    date: '2024-08-20',
    tags: ['Tasting Menu', 'Special Occasion'],
    helpful: 9,
  },
  {
    id: 'rv4',
    restaurantId: 'r2',
    userId: 'u1',
    userName: 'Alex Rivera',
    rating: 5,
    text: 'Best tonkotsu ramen in NYC, full stop. The broth is silky and rich with just the right depth of flavor. The soft-boiled egg was perfect. Lines are worth it.',
    date: '2024-11-01',
    tags: ['Best in NYC', 'Rich Broth'],
    helpful: 28,
  },
  {
    id: 'rv5',
    restaurantId: 'r2',
    userId: 'u2',
    userName: 'Jordan Kim',
    rating: 4,
    text: 'Great ramen, super cozy spot. Can get very crowded but the turnover is quick. The spicy miso is a sleeper hit — order it.',
    date: '2024-10-10',
    tags: ['Cozy', 'Crowded'],
    helpful: 11,
  },
  {
    id: 'rv6',
    restaurantId: 'r3',
    userId: 'u3',
    userName: 'Sam Okafor',
    rating: 5,
    text: 'The brisket was smoky perfection — tender, juicy, with a bark that had real depth. The jalapeño cheddar cornbread is a must. Old-school BBQ done right.',
    date: '2024-09-14',
    tags: ['Best Brisket', 'Comfort Food'],
    helpful: 19,
  },
  {
    id: 'rv7',
    restaurantId: 'r3',
    userId: 'u1',
    userName: 'Alex Rivera',
    rating: 4,
    text: 'Really solid BBQ. Brisket is the star, pulled pork is also great. Mac and cheese could be cheesier. Worth a visit when in the area.',
    date: '2024-07-22',
    tags: ['Solid BBQ', 'Good Sides'],
    helpful: 5,
  },
  {
    id: 'rv8',
    restaurantId: 'r4',
    userId: 'u2',
    userName: 'Jordan Kim',
    rating: 5,
    text: 'Transported to Paris. The croissants are flaky, buttery gold. The steak frites were cooked perfectly medium-rare with a gorgeous bordelaise sauce. The wine list is superb.',
    date: '2024-10-30',
    tags: ['Authentic French', 'Romantic'],
    helpful: 16,
  },
  {
    id: 'rv9',
    restaurantId: 'r4',
    userId: 'u3',
    userName: 'Sam Okafor',
    rating: 3,
    text: 'Food was good but service was a bit slow and formal in a way that felt off. The crème brûlée was excellent though. Location is lovely.',
    date: '2024-09-05',
    tags: ['Average Service'],
    helpful: 3,
  },
  {
    id: 'rv10',
    restaurantId: 'r5',
    userId: 'u1',
    userName: 'Alex Rivera',
    rating: 5,
    text: 'The Kerala fish curry is transcendent. Complex, aromatic, with coconut milk and curry leaf balanced beautifully. Vegetarian options are genuinely exciting — not afterthoughts.',
    date: '2024-11-05',
    tags: ['Best Curry', 'Vegetarian Friendly'],
    helpful: 22,
  },
  {
    id: 'rv11',
    restaurantId: 'r6',
    userId: 'u2',
    userName: 'Jordan Kim',
    rating: 5,
    text: 'The al pastor tacos are incredible. Crispy corn tortillas, perfectly seasoned pork, fresh pineapple. The salsa verde is addictive. Best tacos downtown.',
    date: '2024-10-18',
    tags: ['Best Tacos', 'Late Night'],
    helpful: 31,
  },
  {
    id: 'rv12',
    restaurantId: 'r8',
    userId: 'u3',
    userName: 'Sam Okafor',
    rating: 4,
    text: 'Beautiful seasonal menu. Every ingredient shines. The heirloom tomato salad was a highlight. Wine list is thoughtfully curated. Expensive but worth it for the experience.',
    date: '2024-10-22',
    tags: ['Seasonal', 'Worth the Price'],
    helpful: 14,
  },
];

// ============================================
// HELPER: Compute aggregated ratings per restaurant
// ============================================

export function computeRatingStats(restaurantId, reviews) {
  const rr = reviews.filter(r => r.restaurantId === restaurantId);
  if (rr.length === 0) return { avg: 0, count: 0, breakdown: { 5: 0, 4: 0, 3: 0, 2: 0, 1: 0 } };

  const breakdown = { 5: 0, 4: 0, 3: 0, 2: 0, 1: 0 };
  let total = 0;
  rr.forEach(r => {
    breakdown[r.rating] = (breakdown[r.rating] || 0) + 1;
    total += r.rating;
  });

  return {
    avg: parseFloat((total / rr.length).toFixed(1)),
    count: rr.length,
    breakdown,
  };
}
